name = "Lin_sys"
uuid = "e6a0f38a-315b-492f-a313-a92ae41c612d"
authors = ["Wasserschmitt <iushin.kv@phystech.edu>"]
version = "0.1.0"

[deps]
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
