name = "CTSolverStability"
uuid = "b4eabad2-7273-46f3-ba19-4d5804d9d39e"
authors = ["Wasserschmitt <iushin.kv@phystech.edu>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
